export const users = [
    { id: 1, name: "User1", email: "user1@example.com", role: "customer" },
    { id: 2, name: "User2", email: "user2@example.com", role: "customer" },
    { id: 3, name: "User3", email: "user3@example.com", role: "customer" },
    { id: 4, name: "User4", email: "user4@example.com", role: "customer" },
    { id: 5, name: "User5", email: "user5@example.com", role: "customer" },
    { id: 6, name: "User6", email: "user6@example.com", role: "customer" },
    { id: 7, name: "User7", email: "user7@example.com", role: "customer" },
    { id: 8, name: "User8", email: "user8@example.com", role: "customer" },
    { id: 9, name: "User9", email: "user9@example.com", role: "customer" },
    { id: 10, name: "User10", email: "user10@example.com", role: "customer" },
    { id: 11, name: "User11", email: "user11@example.com", role: "customer" },
    { id: 12, name: "User12", email: "user12@example.com", role: "customer" },
    { id: 13, name: "User13", email: "user13@example.com", role: "customer" },
    { id: 14, name: "User14", email: "user14@example.com", role: "customer" },
    { id: 15, name: "User15", email: "user15@example.com", role: "customer" },
    { id: 16, name: "User16", email: "user16@example.com", role: "delivery" },
    { id: 17, name: "User17", email: "user17@example.com", role: "delivery" },
    { id: 18, name: "User18", email: "user18@example.com", role: "delivery" },
    { id: 19, name: "User19", email: "user19@example.com", role: "delivery" },
    { id: 20, name: "User20", email: "user20@example.com", role: "customer" },
];

export const products = [
    { id: 1, name: "Product1", price: 10.5 },
    { id: 2, name: "Product2", price: 15.0 },
    { id: 3, name: "Product3", price: 7.75 },
    { id: 4, name: "Product4", price: 22.0 },
    { id: 5, name: "Product5", price: 5.5 },
    { id: 6, name: "Product6", price: 18.25 },
    { id: 7, name: "Product7", price: 12.0 },
    { id: 8, name: "Product8", price: 8.5 },
    { id: 9, name: "Product9", price: 20.0 },
    { id: 10, name: "Product10", price: 14.75 },
    { id: 11, name: "Product11", price: 9.0 },
    { id: 12, name: "Product12", price: 16.5 },
    { id: 13, name: "Product13", price: 11.25 },
    { id: 14, name: "Product14", price: 19.0 },
    { id: 15, name: "Product15", price: 6.5 },
    { id: 16, name: "Product16", price: 21.0 },
    { id: 17, name: "Product17", price: 13.5 },
    { id: 18, name: "Product18", price: 17.75 },
    { id: 19, name: "Product19", price: 10.0 },
    { id: 20, name: "Product20", price: 12.5 },
    { id: 21, name: "Product21", price: 9.25 },
    { id: 22, name: "Product22", price: 15.5 },
    { id: 23, name: "Product23", price: 8.0 },
    { id: 24, name: "Product24", price: 20.5 },
    { id: 25, name: "Product25", price: 14.0 },
];

export const admin = {
    id: 1,
    email: "admin1@example.com",
    password: "hashed_password1",
    first_name: "Ahmed",
    last_name: "Ali",
    gender: "male",
    birth_date: "1985-04-12",
    phone: "+201234567890",
    created_at: "2025-01-10",
    date_employed: "2010-06-01",
};
